version: "3"
services:
  # START Backup Service
  backup:
    image: muyajil/borg-backup-service:latest
    environment:
      BORG_USER: ${BORG_USER}
      BORG_HOST: ${BORG_HOST}
      BORG_PORT: ${BORG_PORT}
      BORG_REPO_PATH_ON_HOST: ${BORG_REPO_PATH_ON_HOST}
      BORG_OPTIONS: ${BORG_OPTIONS}
      ARCHIVE_NAME: ${ARCHIVE_NAME}
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
      BORG_KEYS_DIR: /borg_keys
      HOURLY_BACKUPS: 1
      DAILY_BACKUPS: 7
      WEEKLY_BACKUPS: 4
      SSH_KEY_PATH: /id_rsa
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    volumes:
      - ${BACKUP_SOURCE}:/backup_source
      - ${SSH_KEY_PATH}:/id_rsa
      - ${BORG_KEYS_DIR}:/borg_keys
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  # END Backup Service
  # START gphotos-syncer
  gphotos-syncer:
    image: muyajil/gphotos-syncer:latest
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${CONFIG_PATH}:/config
      - ${PHOTOS_PATH}:/download
    environment:
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      CLIENT_SECRET: ${CLIENT_SECRET}
  # END gphotos-syncer
  # START cubebackup
  gsuite-backup:
    image: cubebackup/cubebackup:latest
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - type: volume
        source: ${CUBE_BACKUP_PATH}/config
        target: /opt
      - ${CUBE_BACKUP_PATH}/index:/cube_index
      - ${GSUITE_BACKUP_PATH}:/gsuite_backup
    environment: 
      VIRTUAL_HOST: cubebackup.${TLD}
      LETSENCRYPT_HOST: cubebackup.${TLD}
      VIRTUAL_PORT: 80
    networks:
      - base-network
  # END cubebackup
networks:
  base-network:
    external: true
