version: "3.2"
services:
  # START gphotos-syncer
  gphotos-syncer:
    image: muyajil/gphotos-syncer:latest
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${CONFIG_PATH}:/config
      - ${PHOTOS_PATH}:/download
    environment:
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      CLIENT_SECRET: ${CLIENT_SECRET}
  # END gphotos-syncer
  # START cubebackup
  gsuite-backup:
    image: cubebackup/cubebackup:latest
    restart: unless-stopped
    # user: 1000:1000
    volumes:
      - ${VOLUMES_PATH}/cubebackup/config:/opt/cubebackup/db
      - ${VOLUMES_PATH}/cubebackup/index:/cube_index
      - ${GSUITE_BACKUP_PATH}:/gsuite_backup
    environment: 
      VIRTUAL_HOST: cubebackup.${TLD}
      LETSENCRYPT_HOST: cubebackup.${TLD}
      VIRTUAL_PORT: 80
    networks:
      - base-network
  # END cubebackup
  # START Duplicati
  duplicati:
    image: linuxserver/duplicati:latest
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/London
      VIRTUAL_HOST: duplicati.${TLD}
      LETSENCRYPT_HOST: duplicati.${TLD}
      VIRTUAL_PORT: 8200
      CLI_ARGS: #optional
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    volumes:
      - ${VOLUMES_PATH}/duplicati:/config
      - ${SSH_KEY_PATH}:/id_rsa
      - ./slack_notify.sh:/slack_notify.sh
      - ${BACKUP_SOURCE}:/source
    restart: unless-stopped
    networks:
      - base-network
  # END Duplicati
  # START Duplicacy
  duplicacy:
    image: erichough/duplicacy
    hostname: srv.ajil.ch
    restart: unless-stopped
    user: 0:0
    cap_drop:
      - ALL
    environment:
      VIRTUAL_HOST: duplicacy.${TLD}
      LETSENCRYPT_HOST: duplicacy.${TLD}
      VIRTUAL_PORT: 3875
    volumes:
      - /etc/machine-id:/var/lib/dbus-machine-id:ro
      - ${VOLUMES_PATH}/duplicacy/config:/etc/duplicacy
      - ${VOLUMES_PATH}/duplicacy/cache:/var/cache/duplicacy
      - ${BACKUP_SOURCE}:/storage
    networks:
      - base-network
  # END Duplicacy
networks:
  base-network:
    external: true
