version: "3.2"
services:
  # START cubebackup
  gsuite-backup:
    image: cubebackup/cubebackup:latest
    restart: unless-stopped
    # user: 1000:1000
    volumes:
      - ${VOLUMES_PATH}/cubebackup/config:/opt/cubebackup/db
      - ${VOLUMES_PATH}/cubebackup/index:/cube_index
      - ${VOLUMES_PATH}/cubebackup/gsuite_backup:/gsuite_backup
    environment: 
      VIRTUAL_HOST: cubebackup.${TLD}
      LETSENCRYPT_HOST: cubebackup.${TLD}
      VIRTUAL_PORT: 80
    networks:
      - base-network
  # END cubebackup
  # START Duplicacy
  duplicacy:
    image: saspus/duplicacy-web:latest
    hostname: srv.ajil.ch
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: duplicacy.${TLD}
      LETSENCRYPT_HOST: duplicacy.${TLD}
      VIRTUAL_PORT: 3875
      USR_ID: 0
      GRP_ID: 0
      TZ: Europe/Zurich
      DWE_PASSWORD: ${DUPLICACY_PW}
    volumes:
      - ${VOLUMES_PATH}/duplicacy/config:/config
      - ${VOLUMES_PATH}/duplicacy/cache:/cache
      - ${VOLUMES_PATH}/duplicacy/logs:/logs
      - ${BACKUP_SOURCE}:/backuproot:ro
      - ${SSH_KEY_PATH}:/id_rsa
    networks:
      - base-network
  # END Duplicacy
networks:
  base-network:
    external: true
